# para instalar algo no tmux use prefix + I
unbind r
bind r source-file ~/.tmux.conf
set -g prefix C-s
bind-key Escape send-keys Escape
set -s escape-time 0

bind-key c new-window
bind-key u new-session
bind-key d  kill-window
bind-key x confirm-before kill-session
bind-key  ] split-window -h
bind-key [ split-window
bind-key  n next-window
bind-key  v kill-pane
bind-key  p previous-window
bind-key b break-pane


# act like vim
setw -g mode-keys vi
bind-key C-h select-pane -L
bind-key C-j select-pane -D
bind-key C-k select-pane -U
bind-key C-l select-pane -R

# List of plugins
set -g @plugin 'tmux-plugins/tpm'



# set -g @plugin 'dracula/tmux'
# set -g @dracula-show-powerline true
# set -g @dracula-fixed-location "BRASIL"
# set -g @dracula-plugins "weather"
# set -g @dracula-show-flags true
# set -g @dracula-show-left-icon session
set -g status-position bottom
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'erikw/tmux-powerline'
set -g @plugin "tmux-plugins/tmux-battery"
set -g @plugin 'jimeh/tmux-themepack'
# set -g @themepack 'powerline/double/magenta'
# set -g @themepack 'powerline/default/gray'

set -g @plugin 'wfxr/tmux-power'
set -g @tmux_power_theme '#606060'
set -g @tmux_power_date_icon ''
set -g @tmux_power_time_icon ''
set -g @tmux_power_user_icon ' '
set -g @tmux_power_session_icon ' '
set -g @tmux_power_show_upload_speed    false
set -g @tmux_power_show_download_speed  false
set -g @tmux_power_show_web_reachable   false
set -g @tmux_power_right_arrow_icon       "" #    
set -g @tmux_power_left_arrow_icon        "" #    


# Habilitar suporte a 256 cores e cores verdadeiras
set-option -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

set -g @plugin 'sainnhe/tmux-fzf'
TMUX_FZF_LAUNCH_KEY="f"



# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
