
version = 2
console_title_template = '{{ .Shell }} in {{ .Folder }}'
final_space = true 

[[blocks]]
  type = "prompt"
  alignment = "left"


  [[blocks.segments]]
    type = "os"
    template = "{{.Icon}}"
    background = "#808080" # #111111 #181818 #808080
    foreground = "#FFFFFF" #9B6BDF
    trailing_diamond = "\ue0b4 "
    leading_diamond = "\ue0b6" #so remover essa seta
    style = "diamond"

    [properties]
    macos = "mac"


  [[blocks.segments]]
  type = "path"
  background = "#181818" # #111111 #181818
  foreground = "#FFFFFF" # #3EC669 #FFA86B #9B6BDF
  leading_diamond = "\ue0b6"
  trailing_diamond = "\ue0b4"
  style = "diamond"
  template = "\ue5ff {{ .Path }}"
    [blocks.segments.properties]
      style = 'powerlevel'
      folder_icon = ''
      home_icon = ' '
      max_width = 20
      cycle = ['#9B6BDF', '#a6a3a6', '#9B6BDF'] #cyan, magenta, blue #a6a3a6


[[blocks]]
  type = "prompt"
  alignment = "right"




  [[blocks.segments]]
    type = "git"
    style = "diamond"
    foreground = "#FFFFFF" #43CCEA #FFA86B
    background = "#111111" # #111111 #181818
    leading_diamond = " \ue0b6"
    trailing_diamond = "\ue0b4"
    foreground_templates = [
      "{{ if or (.Working.Changed) (.Staging.Changed) }}#FFFFFF{{ end }}", # #FFEB3B
      "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#FFCC80{{ end }}",
      "{{ if gt .Ahead 0 }}#B388FF{{ end }}",
      "{{ if gt .Behind 0 }}#B388FB{{ end }}"
    ]
    template = "<#FFFFFF>{{ url .UpstreamIcon .UpstreamURL }}</> {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  <#22d3ee> ?{{.Working.Untracked}}</> ~{{ .Working.Modified }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}<#34d399>  {{ .StashCount }}</>{{ end }}"

    [blocks.segments.properties]
      fetch_status = true
      branch_max_length = 25
      fetch_upstream_icon = true
      truncate_symbol = '…'
      branch_icon = ' '
      commit_icon = '@'


      [properties.untracked_modes]
      "/Users/user/Projects/oh-my-posh/" = "no"




  [[blocks.segments]]
  type = "python"
  background = "#181818"
  foreground = "#E4F34A"
  leading_diamond = " \ue0b6"
  trailing_diamond = "\ue0b4"
  style = "diamond"
  template = "  {{ .Major }}.{{ .Minor }} "


  [[blocks.segments]]
  type = "node"
  background = "#181818" # #424242
  foreground = "#42E66C"
  leading_diamond = " \ue0b6"
  trailing_diamond = "\ue0b4"
  style = "diamond"
  template = "  {{ .Major }}.{{ .Minor }} "

  [[blocks.segments]]
  type = "ruby"
  background = "#181818"
  foreground = "#E64747"
  leading_diamond = " \ue0b6"
  trailing_diamond = "\ue0b4"
  style = "diamond"
  template = "  {{ .Major }}.{{ .Minor }} "

  [[blocks.segments]]
  type = "java"
  background = "#181818"
  foreground = "#E64747"
  leading_diamond = " \ue0b6"
  trailing_diamond = "\ue0b4"
  style = "diamond"
  template = "  {{ .Major }}.{{ .Minor }} "


  [[blocks.segments]]
  type = "php"
  background = "#181818"
  foreground = "#A872C9"
  leading_diamond = " \ue0b6"
  trailing_diamond = "\ue0b4"
  style = "diamond"
  template = "  {{ .Major }}.{{ .Minor }} "

  [[blocks.segments]]
  type = "typescript"
  background = "#181818" # #4063D8
  foreground = "#007ACC"
  leading_diamond = " \ue0b6"
  trailing_diamond = "\ue0b4"
  style = "diamond"
  template = " 󰛦 {{ .Major }}.{{ .Minor }} "


  [[blocks.segments]]
  type = "rust"
  background = "#181818"
  foreground = "#FFFFFF"
  leading_diamond = " \ue0b6"
  trailing_diamond = "\ue0b4"
  style = "diamond"
  template = "  {{ .Major }}.{{ .Minor }} "


  [[blocks.segments]]
  type = "dart"
  background = "#181818"
  foreground = "#00b4AB"
  leading_diamond = " \ue0b6"
  trailing_diamond = "\ue0b4"
  style = "diamond"
  template = "  {{ .Major }}.{{ .Minor }} "


   [[blocks.segments]]
    type = "status"
    background = "transparent"
    foreground = "#606060" # #606060 #9B6BDF
    leading_diamond = "\ue0b6"
    trailing_diamond = "\ue0b4 "
    foreground_templates = [ "{{ if gt .Code 0 }}#E38073{{ end }}" ]
    template = " " ## 󰀦  

      [blocks.segments.properties]
      always_enabled = true

  # [[blocks.segments]]
  # type = "battery"
  # background = "#111111"
  # foreground = "#9B6BDF"
  # leading_diamond = " \ue0b6"
  # trailing_diamond = "\ue0b4"
  # style = "diamond"
  # template = "{{ if not .Error }}{{ .Icon }}{{ .Percentage }}{{ end }}{{ .Error }}"
  #   [blocks.segments.properties]
  #   charged_icon = "\u25cf "
  #   charging_icon = "\u21e1 "
  #   discharging_icon = "\u21e3 "
  # foreground_templates = [
  #   "{{if eq \"Charging\" .State.String}}#40c4ff{{end}}",
  #   "{{if eq \"Discharging\" .State.String}}#ff5722{{end}}",
  #   "{{if eq \"Full\" .State.String}}#4caf50{{end}}"
  # ]



  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'yellow'
    background = 'transparent'
    template = '{{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 5000



[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true


  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}#E38073{{end}}",
      "{{if eq .Code 0}}#9B6BDF{{end}}",
    ]   
    background = 'transparent'
    template = '❯'

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}red{{end}}",
    "{{if eq .Code 0}}magenta{{end}}",
  ]
  background = 'transparent'
  template = '❯ '

[secondary_prompt]
  foreground = '#FFFFFF' # magenta
  background = 'transparent'
  template = '❯❯ '
