console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[secondary_prompt]
  template = '❯❯ '
  foreground = '#9B6BDF'
  background = 'transparent'

[transient_prompt]
  template = '❯ '
  background = 'transparent'
  foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}magenta{{end}}']

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '{{.Icon}}'
    type = 'os'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    foreground = '#FFFFFF'
    background = 'transparent'
    type = 'path'

    [blocks.segments.properties]
      cache_duration = 'none'
      cycle = ['cyan', '#a6a3a6', '#9B6BDF']
      folder_icon = ''
      home_icon = ' '
      max_width = 20
      style = 'powerlevel'

  [[blocks.segments]]
    template = '<#FFFFFF>{{ url .UpstreamIcon .UpstreamURL }}</> {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  <#22d3ee> ?{{.Working.Untracked}}</> ~{{ .Working.Modified }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}<#34d399>  {{ .StashCount }}</>{{ end }}'
    foreground = '#FFFFFF'
    background = 'transparent'
    type = 'git'
    style = 'powerline'
    foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}#FFFFFF{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#FFCC80{{ end }}', '{{ if gt .Ahead 0 }}#B388FF{{ end }}', '{{ if gt .Behind 0 }}#B388FB{{ end }}']

    [blocks.segments.properties]
      branch_icon = ' '
      branch_max_length = 25
      cache_duration = 'none'
      commit_icon = '@'
      fetch_status = true
      fetch_upstream_icon = true
      truncate_symbol = '…'

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    template = '  {{ .Major }}.{{ .Minor }} '
    foreground = '#ffffff'
    powerline_symbol = ''
    background = '#422251'
    type = 'elixir'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '  {{ .Major }}.{{ .Minor }} '
    foreground = '#6CA35E'
    type = 'node'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '  {{ .Major }}.{{ .Minor }} '
    foreground = '#A872C9'
    type = 'php'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '  {{ .Major }}.{{ .Minor }} '
    foreground = '#CC342D'
    type = 'ruby'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '  {{ .Major }}.{{ .Minor }} '
    foreground = '#FFFF00'
    type = 'python'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '  {{ .Major }}.{{ .Minor }} '
    foreground = '#FF0000'
    type = 'java'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' 󰛦 {{ .Major }}.{{ .Minor }} '
    foreground = '#007ACC'
    type = 'typescript'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '  {{ .Major }}.{{ .Minor }} '
    foreground = '#000000'
    type = 'rust'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '  {{ .Major }}.{{ .Minor }} '
    foreground = '#00B4AB'
    type = 'dart'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'

  # [[blocks.segments]]
  #   template = ' '
  #   foreground = '#606060'
  #   type = 'status'
  #   foreground_templates = ['{{ if gt .Code 0 }}#E38073{{ end }}']

  #   [blocks.segments.properties]
  #     always_enabled = true
  #     cache_duration = 'none'

  [[blocks.segments]]
    template = '{{ .FormattedMs }}'
    foreground = 'yellow'
    background = 'transparent'
    type = 'executiontime'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      threshold = 5000

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '❯'
    background = 'transparent'
    type = 'text'
    style = 'plain'
    foreground_templates = ['{{if gt .Code 0}}#E38073{{end}}', '{{if eq .Code 0}}#9B6BDF{{end}}']

    [blocks.segments.properties]
      cache_duration = 'none'
