reload('user.plugins')
reload('user.dashboard')
reload('user.keybinds')
reload('user.which_keys')
reload('user.colorscheme')
reload('user.lualine')
reload('user.copilot')
reload('user.codeium')
reload('user.prettier')
reload('user.discord')
reload('user.notify')
reload('user.renamer')
reload('user.telescope_browser')
reload('user.harpoon')
reload('user.neotest')
reload('user.obsidian')
reload('user.dap')
reload('user.incline')
require("mason-nvim-dap").setup()
require('avante_lib').load()
vim.opt.clipboard = "unnamedplus"
-- lvim.format_on_save.enabled = true
vim.opt.shiftwidth = 3   -- Tamanho do indent (equivale ao tamanho do tab)
vim.opt.tabstop = 3      -- Número de espaços que um tab representa
vim.opt.expandtab = true -- Converter tabs para espaços
